services:
  - type: web
    name: awt-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: GCS_PROJECT_ID
        sync: false
      - key: GCS_BUCKET_NAME
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false

