name: AWT Data Sync

on:
  schedule:
    # Run daily at 5 AM UTC
    - cron: '0 5 * * *'
  workflow_dispatch: # Allow manual runs

jobs:
  sync-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Google Cloud credentials
      run: |
        # Copy the credentials file from repo
        cp .github/gcp-credentials.json gcp-key.json
        # Validate the JSON is properly formatted
        python -c "import json; data=json.load(open('gcp-key.json')); print(f'✓ JSON valid. Private key: {len(data[\"private_key\"])} chars, Project: {data[\"project_id\"]}')" || (echo "JSON invalid" && cat gcp-key.json && exit 1)
      shell: bash

    - name: Run AWT data sync
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-key.json
        AWT_USERNAME: ${{ vars.AWT_USERNAME || 'your_username_here' }}
        AWT_PASSWORD: ${{ vars.AWT_PASSWORD || 'your_password_here' }}
        AWT_API_KEY: ${{ vars.AWT_API_KEY || 'your_api_key_here' }}
        GCS_BUCKET_NAME: ${{ vars.GCS_BUCKET_NAME || 'your_bucket_name' }}
        GCS_PROJECT_ID: awt-api-472312
      run: |
        python awt_data_sync.py
